# PV для Prometheus (10Gi)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv-10gi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /var/local-storage/monitoring/prometheus
    type: DirectoryOrCreate

---
# PV для Grafana (2Gi)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv-2gi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /var/local-storage/monitoring/grafana
    type: DirectoryOrCreate

---
# PV для AlertManager (1Gi)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv-1gi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /var/local-storage/monitoring/alertmanager
    type: DirectoryOrCreate
