# Minimal PVs for ultra lightweight setup

# PV для Prometheus (2Gi instead of 10Gi)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv-2gi-prometheus
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /var/local-storage/monitoring/prometheus
    type: DirectoryOrCreate

---
# PV для Grafana (1Gi)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv-1gi-grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /var/local-storage/monitoring/grafana
    type: DirectoryOrCreate
