apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-infrastructure
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/baborok/ArgoCD-practice.git
    targetRevision: HEAD
    path: infrastructure/storage
    
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
