# Fixed: Remove root user from initContainers to comply with security policies

ingress:
  enabled: true
  grafana:
    path: /grafana
  prometheus:
    path: /prometheus

kube-prometheus-stack:
  grafana:
    adminPassword: "admin123"
    
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: local-storage
    
    # Init container WITHOUT root privileges
    initContainers:
      - name: fix-permissions
        image: busybox:1.36
        command: ['sh', '-c', 'echo "Checking permissions..." && ls -la /var/lib/grafana || true']
        volumeMounts:
          - name: storage
            mountPath: /var/lib/grafana
        # Remove securityContext with runAsUser: 0

  prometheus:
    enabled: true
    
    prometheusSpec:
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      
      retention: 3d
      retentionSize: 1GB
      
      # Init container WITHOUT root privileges
      initContainers:
        - name: fix-prometheus-permissions
          image: busybox:1.36
          command: ['sh', '-c', 'echo "Checking Prometheus permissions..." && ls -la /prometheus || true']
          volumeMounts:
            - name: prometheus-monitoring-stack-kube-prom-prometheus-db
              mountPath: /prometheus
          # Remove securityContext with runAsUser: 0
      
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      
      scrapeInterval: 120s
      serviceMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: true
  defaultRules:
    create: false

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
