# Production-ready persistent monitoring configuration

ingress:
  enabled: true
  grafana:
    path: /grafana
  prometheus:
    path: /prometheus  
  alertmanager:
    path: /alertmanager

kube-prometheus-stack:
  # Grafana with persistence
  grafana:
    adminPassword: "monitoring-admin123"
    
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    
    persistence:
      enabled: true
      size: 2Gi
      storageClassName: local-storage
    
    sidecar:
      dashboards:
        enabled: true
      datasources:
        enabled: true
        
    grafana.ini:
      server:
        root_url: http://192.168.1.100/grafana
      analytics:
        check_for_updates: false

  # Prometheus with persistence
  prometheus:
    enabled: true
    
    prometheusSpec:
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      
      retention: 15d
      retentionSize: 8GB
      
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
      
      scrapeInterval: 30s
      evaluationInterval: 30s
      serviceMonitorSelectorNilUsesHelmValues: false

  # AlertManager with persistence
  alertmanager:
    enabled: true
    
    alertmanagerSpec:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
          
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
      
      retention: 168h

  # Exporters
  nodeExporter:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 128Mi

  kubeStateMetrics:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 256Mi

  # Alerting rules
  defaultRules:
    create: true
    rules:
      alertmanager: true
      general: true
      k8s: true
      kubernetesApps: true
      kubernetesResources: true
      node: true
      prometheus: true
