replicaCount: 1

image:
  repository: nitheesh86/microservice-recommendation
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: "2048Mi"
  requests:
    cpu: "1000m"
    memory: "1024Mi"
