{{- if .Values.ingress.enabled }}
# Grafana Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    component: grafana
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.grafana.path | default "/grafana" }}(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-kube-prometheus-stack-grafana
            port:
              number: 80
---
# Prometheus Ingress  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    component: prometheus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.prometheus.path | default "/prometheus" }}(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-kube-prometheus-stack-prometheus
            port:
              number: 9090
---
# AlertManager Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    component: alertmanager
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.alertmanager.path | default "/alertmanager" }}(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-kube-prometheus-stack-alertmanager
            port:
              number: 9093
{{- end }}
