{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-microservices
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      prometheus.io/scrape: "true"  # Label to add to services
  namespaceSelector:
    matchNames:
    - dev
    - staging  
    - prod
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    honorLabels: true
---
# ArgoCD ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-argocd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  namespaceSelector:
    matchNames:
    - argocd
  endpoints:
  - port: metrics
    interval: 30s
{{- end }}
